### ISSUE TITLE
P-Ⅲ曲线的绘制

### ISSUE THREAD

**Issue by AndrewHu00** [tanukihee/HessianProbabilityGrid#1]
我用IDLE和PyCharm都没有运行出来结果，会报有关texlive有关的错误，可以联系您交流一下吗，谢谢！
我的邮箱：hujun@stu.ouc.edu.cn

**Comment by tanukihee** [comment]
没想到还真有人用……你先试试不用 texlive，把第 14 行的 `USE_TEX` 改成 `false` 看看有没有结果

**Comment by tanukihee** [comment]
这玩意儿是我大学啥也不懂的时候写的😂，现在回过头看问题好大……（

**Comment by AndrewHu00** [comment]
> 没想到还真有人用……你先试试不用 texlive，把第 14 行的 `USE_TEX` 改成 `false` 看看有没有结果

改了之后不会出图啊，只算出来三个参数。
![image](https://user-images.githubusercontent.com/116559439/197808615-ed2e229c-a1d7-47de-91df-04e902c187e1.png)

**Comment by tanukihee** [comment]
图片保存的语句在第 341/363 行，你看看目录下有无保存下来的图片

尝试改变保存的文件格式（如换成 jpg），或者改成 `data.fig.show()` （是这个方法来着？）试试

**Comment by AndrewHu00** [comment]
> 图片保存的语句在第 341/363 行，你看看目录下有无保存下来的图片
> 
> 尝试改变保存的文件格式（如换成 jpg），或者改成 `data.fig.show()` （是这个方法来着？）试试



> 图片保存的语句在第 341/363 行，你看看目录下有无保存下来的图片
> 
> 尝试改变保存的文件格式（如换成 jpg），或者改成 `data.fig.show()` （是这个方法来着？）试试

ok，现在程序可以用了，感谢！有个小问题，怎么根据设计频率求设计参数呢？

**Comment by tanukihee** [comment]
281 行的 `prob_to_value` 方法与 301 行的 `value_to_prob` 方法可以进行频率和参数的互相转换。使用示例：`data.prob_to_value(5)` ，求 20 年一遇洪水参数。更多使用方法可以看一下方法底下的文档。

**Comment by AndrewHu00** [comment]
请问一下优化适线的遵从的规则是怎么样的（依据什么原理选取Cs,Cv值）？我知道的两种，一个是选取合适Cs/Cv值，使每个点误差的平方和（或绝对值）最小，这样每个点对适线的贡献是一样的；一种是使各点的 绝对误差/该点频率 之和最小， 这样放大了头部的点对适线的影响，使得极端水位推求更精确。不知道这个程序依据什么原则适线的呢？

**Comment by tanukihee** [comment]
离差平方和最小原则，README 里面有讲
